// 让 :capacitor-android 等子模块也走国内镜像。
// 阿里云镜像
gradle.projectsLoaded {
    rootProject.allprojects { project ->
        project.buildscript {
            repositories {
                maven { url 'https://maven.aliyun.com/repository/public' }
                maven { url 'https://maven.aliyun.com/repository/google' }
                maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
            }
        }
        project.repositories {
            maven { url 'https://maven.aliyun.com/repository/public' }
            maven { url 'https://maven.aliyun.com/repository/google' }
        }
    }
}
